tap "ankitpokhrel/jira-cli"

# Core utilities
brew "bat"
brew "colima"
brew "coreutils"
brew "eza"
brew "fd"
brew "fzf"
brew "htop"
brew "jq"
brew "mas"
brew "neovim"
brew "ripgrep"
brew "starship"
brew "stow"
brew "tree"
brew "wget"
brew "zsh-syntax-highlighting"

# Git tools
brew "gh"
brew "git"
brew "git-delta"
brew "glab"
brew "tig"

# Docker & Kubernetes
brew "docker"
brew "docker-buildx"
brew "docker-compose"
brew "helm"
brew "kubernetes-cli"

# Database
brew "pgcli"
brew "postgresql@14", restart_service: :changed

# Development tools
brew "fnm"
brew "jira-cli"
brew "libmagic"
brew "pigz"
brew "poetry"
brew "poppler"
brew "pybind11"
brew "python@3.12"
brew "qpdf"
brew "re2"
brew "tmux"
brew "tmuxinator"
brew "uv"
brew "yamllint"
brew "zbar"

# Casks - Applications
cask "1password"
cask "brave-browser"
cask "firefox"
cask "google-chrome"
cask "iterm2"
cask "karabiner-elements"
cask "keyboardcleantool"
cask "ngrok"
cask "obsidian"
cask "openlens"
cask "postman"
cask "slack"
cask "visual-studio-code"
cask "vlc"

# Casks - Fonts
cask "font-cascadia-code-nerd-font"
cask "font-fira-code"
cask "font-hack-nerd-font"
cask "font-meslo-lg-nerd-font"

# VSCode Extensions
vscode "ancientlord.nightowl-theme"
vscode "avetis.tokyo-night"
vscode "ckolkman.vscode-postgres"
vscode "codeium.codeium"
vscode "dbaeumer.vscode-eslint"
vscode "docker.docker"
vscode "donjayamanne.python-environment-manager"
vscode "eamodio.gitlens"
vscode "enkia.tokyo-night"
vscode "esbenp.prettier-vscode"
vscode "fnando.linter"
vscode "foxundermoon.shell-format"
vscode "github.copilot"
vscode "github.copilot-chat"
vscode "github.vscode-github-actions"
vscode "gitlab.gitlab-workflow"
vscode "gruntfuggly.todo-tree"
vscode "hashicorp.terraform"
vscode "kennylong.kubernetes-yaml-formatter"
vscode "liviuschera.noctis"
vscode "mquandalle.graphql"
vscode "ms-azuretools.vscode-containers"
vscode "ms-azuretools.vscode-docker"
vscode "ms-kubernetes-tools.vscode-kubernetes-tools"
vscode "ms-playwright.playwright"
vscode "ms-python.debugpy"
vscode "ms-python.python"
vscode "ms-python.vscode-pylance"
vscode "ms-python.vscode-python-envs"
vscode "orta.vscode-twoslash-queries"
vscode "pamaron.pytest-runner"
vscode "redhat.vscode-yaml"
vscode "richie5um2.vscode-sort-json"
vscode "robbowen.synthwave-vscode"
vscode "snowflake.snowflake-vsc"
vscode "sourcegraph.amp"
vscode "syler.sass-indented"
vscode "timonwong.shellcheck"
vscode "unifiedjs.vscode-mdx"
vscode "visualstudioexptteam.intellicode-api-usage-examples"
vscode "visualstudioexptteam.vscodeintellicode"
vscode "vscode-icons-team.vscode-icons"
vscode "wayou.file-icons-mac"
vscode "wesbos.theme-cobalt2"
vscode "xyc.vscode-mdx-preview"
vscode "yoavbls.pretty-ts-errors"
