export SYM_MR=$'\U00F04C2'
export SYM_SEPARATOR=$'\u001f'
export SYM_CI_SUCCESS=$'\uf058'
export SYM_CI_WARNING=$'\uea6c'
export SYM_CI_FAILED=$'\uf530'
export SYM_CI_RUNNING=$'\U00F0996'
export SYM_CI_CANCELLED=$'\U00F073A'
export SYM_EYE=$'\uf06e'
export SYM_EYE_CHECK=$'\U00F0D04'
export SYM_LINE_HORIZONTAL=$'\uf45b'

export SYM_ARROW_UP=$'\ueaa1'
export SYM_ARROW_DOWN=$'\uea9a'

export SYM_GIT_COMPARE=$'\uf47f'
export SYM_GIT_BRANCH=$'\ue725'
