# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true

format="""$battery$directory$git_branch$git_status$git_state$fill $nodejs $time$line_break$character"""

continuation_prompt = '▶▶ '

[fill]
symbol = '·'
style = 'fg:purple dimmed'

[time]
disabled = false

[nodejs]
symbol = ''
format = 'via [$symbol $version](yellow bold)'

[character]
success_symbol = '[](bold bright-green)'

[[battery.display]]
threshold = 50

[directory]
format = '[ ~]($style)[$path]($style)[$read_only]($read_only_style) '
truncation_symbol = "/…/"
home_symbol = ''



